name: CI tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda install clingo
        shell: bash -l {0}
        run: |
          conda install -c potassco clingo=5.5.0
          conda install -c potassco clingo-dl=1.2.0
      - name: Build
        run: |
          export CLINGO_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          export CLINGO_DL_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          cargo build --verbose
      - name: Run tests
        run: |
          export CLINGO_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          export CLINGO_DL_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          export LD_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          cargo test --verbose
