name: CI tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          export CLINGO_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          export CLINGO_DL_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          cargo build --verbose
      - name: Run tests
        run: |
          export CLINGO_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          export CLINGO_DL_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          cargo test --verbose
